name       : zelda-roth-se
version    : 1.11.0
release    : 1
source     :
    - https://github.com/christopho/zelda_roth_se/archive/v1.1.0.tar.gz : 99554f95fbee0abe4314b64bb8048fad657e279483206451060a741bef65b544
license    :
    - CC-BY-SA-3.0
    - GPL-2.0
    - GPL-3.0
component  : games.rpg
summary    : Zelda - Return of the Hylian SE - a remake of the original Zelda Return of the Hylian, a short and pleasant fangame from Vincent Jouillat.
description: |
    Zelda - Return of the Hylian SE - a remake of the original Zelda Return of the Hylian, a short and pleasant fangame from Vincent Jouillat.
rundeps  :
    - solarus
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
    for i in 16 24 32 48 64 128 256 512 1024; do \
        install -D -m 00644 data/logos/icon_$i.png $installdir/usr/share/icons/hicolor/"$i"x"$i"/apps/zelda-roth-se.png; \
    done 
    install -D -m 00644 $pkgfiles/zelda-roth-se.desktop $installdir/usr/share/applications/zelda-roth-se.desktop