name       : zelda-roth-se
version    : 1.2.1
release    : 6
source     :
    - https://gitlab.com/solarus-games/zelda-roth-se/-/archive/v1.2.1/zelda-roth-se-v1.2.1.tar.bz2 : 1cff44fe97eab1327a0c0d11107ca10ea983a652c4780487f00f2660a6ab23c0
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : games.rpg
summary    : Zelda - Return of the Hylian SE - a remake of the original Zelda Return of the Hylian, a short and pleasant fangame from Vincent Jouillat.
description: |
    Zelda - Return of the Hylian SE - a remake of the original Zelda Return of the Hylian, a short and pleasant fangame from Vincent Jouillat.
rundeps    :
    - solarus
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
    for i in 16 24 32 48 64 128 256 512 1024; do \
        install -D -m 00644 data/logos/icon_$i.png $installdir/usr/share/icons/hicolor/"$i"x"$i"/apps/zelda-roth-se.png; \
    done
    install -D -m 00644 $pkgfiles/zelda-roth-se.desktop $installdir/usr/share/applications/zelda-roth-se.desktop
